version: '3.9'

services:
  eng-analytics:
    build:
      context: .
      dockerfile: Services/eng-analytics/app/Dockerfile
    container_name: eng-analytics
    ports:
      - "5007:5007"
    volumes:
      - ./Services/eng-analytics/app:/app
    restart: unless-stopped

  eng-billing:
    build:
      context: .
      dockerfile: Services/eng-billing/app/Dockerfile
    container_name: eng-billing
    ports:
      - "5003:5003"
    volumes:
      - ./Services/eng-billing/app:/app
    restart: unless-stopped

  eng-compliance:
    build:
      context: .
      dockerfile: Services/eng-compliance/app/Dockerfile
    container_name: eng-compliance
    ports:
      - "5004:5004"
    volumes:
      - ./Services/eng-compliance/app:/app
    restart: unless-stopped

  eng-drafting:
    build:
      context: .
      dockerfile: Services/eng-drafting/app/Dockerfile
    container_name: eng-drafting
    ports:
      - "5001:5001"
    volumes:
      - ./Services/eng-drafting/app:/app
    restart: unless-stopped

  eng-engagement:
    build:
      context: .
      dockerfile: Services/eng-engagement/app/Dockerfile
    container_name: eng-engagement
    ports:
      - "5006:5006"
    volumes:
      - ./Services/eng-engagement/app:/app
    restart: unless-stopped

  eng-identity:
    build:
      context: .
      dockerfile: Services/eng-identity/app/Dockerfile
    container_name: eng-identity
    ports:
      - "5000:5000"
    volumes:
      - ./Services/eng-identity/app:/app
    restart: unless-stopped

  eng-lifecycle:
    build:
      context: .
      dockerfile: Services/eng-lifecycle/app/Dockerfile
    container_name: eng-lifecycle
    ports:
      - "5005:5005"
    volumes:
      - ./Services/eng-lifecycle/app:/app
    restart: unless-stopped

  eng-vault:
    build:
      context: .
      dockerfile: Services/eng-vault/app/Dockerfile
    container_name: eng-vault
    ports:
      - "5002:5002"
    volumes:
      - ./Services/eng-vault/app:/app
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80" # Expose on 8080 to avoid conflict with Nginx
    volumes:
      - ./assetarc-theme:/var/www/html/wp-content/themes/assetarc-theme
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
      - eng-identity
      - eng-lifecycle
    restart: unless-stopped

volumes:
  db_data:
