openapi: 3.0.3
info:
  title: AssetArc  Identity & Access (E1)
  version: 1.0.0
servers:
  - url: https://auth.example.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /auth/request-otp:
    post:
      summary: Issue OTP to email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string, format: email }
      responses:
        '200': { description: OK }
  /auth/verify-otp:
    post:
      summary: Verify OTP and set cookies / return JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                code: { type: string }
      responses:
        '200': { description: OK }
  /auth/refresh:
    post:
      summary: Rotate access token
      responses:
        '200': { description: OK }
  /auth/user:
    get:
      summary: Current user
      security: [ { bearerAuth: [] } ]
      responses:
        '200': { description: OK }
  /gateway/routes:
    get:
      summary: Service discovery for frontends
      responses:
        '200': { description: Routes map }
  /admin/users/{id}:
    patch:
      summary: Update user (role, activation)
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                role: { type: string, enum: [owner_admin, advisor, client] }
                is_active: { type: boolean }
      responses:
        '200': { description: Updated }
